- hosts: localhost
  gather_facts: true
  roles:
    - { role: packages, tags: [always, core] }
    - { role: dotfiles, tags: [always, core] }
    - { role: rustup, tags: [always, core, lang] }
    - { role: golang, tags: [always, core, lang] }
    - { role: nodejs, tags: [never, lang, node] }
    - { role: neovim, tags: [never, neovim] }
    - { role: docker, tags: [never, docker] }    
