- hosts: localhost
  gather_facts: true
  roles:
    - { role: packages, tags: core }
    - { role: dotfiles, tags: core }
    - { role: rustup, tags: core }
    - { role: golang, tags: core }
    - { role: nodejs, tags: core }
    - { role: neovim, tags: neovim }
