---
- name: Update the system
  become: true
  apt:
    upgrade: full
    update_cache: yes
  tags:
    - core

- name: Install base packages
  become: true
  apt:
    name:
      - bash-completion
      - htop
      - vim
      - nano
      - sudo
      - python3
      - python3-pip
      - python3-virtualenv
      - python3-venv
      - qemu-guest-agent
      - build-essential
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - lsb-release
      - libtool-bin
      - gettext
      - rsync
      - cmake
      - meson
      - ninja-build
      - unzip
      - tmux
      - pkg-config
  tags:
  - core



