---
- name: download nodejs-lts
  shell: >
    set -ex &&
      curl -4 -L -O "https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz" &&
      tar xvf node-v22.14.0-linux-x64.tar.xz &&
      mv node-v22.14.0-linux-x64.tar.xz /home/cmte/.node
      

