---
- name: check if rustup already present
  command: /home/cmte/.cargo/bin/rustup -V
  register: rustup_already_downloaded
  ignore_errors: true

- name: install rustup system requirements
  become: true
  apt:
    name: 
      - curl
      - build-essential
      - make
      - acl
    state: latest
    update_cache: true

- name: Define rustup user home
  ansible.builtin.set_fact:
    rustup_user_home: "/home/cmte"
    rustup_exe: "/home/cmte/.cargo/bin/rustup"

- name: install rustup
  shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}/bin/rustup"
    executable: /bin/bash
  when: rustup_already_downloaded != 0

- name: set and update default profile
  shell: |
    set -ex
    /home/cmte/.cargo/bin/rustup update stable &&
    /home/cmte/.cargo/bin/rustup default stable
