---
- name: check if neovim exists
  stat:
    path: /usr/bin/nvim
  register: nvim_path


- name: install plug
  shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: clone neovim repository
  git:
    repo: https://github.com/neovim/neovim
    dest: /home/cmte/r/neovim
  tags:
    - neovim

- name: build neovim
  shell: |
    cd /home/cmte/r/neovim && make CMAKE_BUILD_TYPE=Release -j 8
  tags:
    - neovim
  when: not nvim_path.stat.exists


- name: install neovim
  become: true
  shell: |
    cd /home/cmte/r/neovim && make install
  tags:
    - neovim
  when: not nvim_path.stat.exists


